### ISSUE TITLE
Merge project README.md and docs main page

### ISSUE THREAD

**Issue by FrankGrimm** [FrankGrimm/omen#48]
Maintaining both doesn't make sense and leaves the main readme in a relatively useless state. While at it also change the gh-pages template, the current one seems tedious to read.

**Comment by imanishbarnwal** [comment]
Hello @FrankGrimm, can I take this issue?

**Comment by FrankGrimm** [comment]
Heya @imanishbarnwal thanks for the offer. At the moment I was just looking at quickly changing this in the project settings, appreciate it though. If you're keen on giving it a shot or have a good suggestion for a better github pages templates feel free to send a PR though, sure.

I wouldn't put much effort in it at this stage to be honest, a better documentation will likely make more sense once the project is a bit more fleshed out and feature complete.

**Comment by imanishbarnwal** [comment]
> Heya @imanishbarnwal thanks for the offer. At the moment I was just looking at quickly changing this in the project settings, appreciate it though. If you're keen on giving it a shot or have a good suggestion for a better github pages templates feel free to send a PR though, sure.
> 
> I wouldn't put much effort in it at this stage to be honest, a better documentation will likely make more sense once the project is a bit more fleshed out and feature complete.

Okay, I will look into it, means, for now, the merge of doc and README.md is not required?

**Comment by FrankGrimm** [comment]
Yeah, pretty much, the issue is just a reminder essentially. Thank you though.
